steps:

- id: "Build Docker Container Image"
  name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'eu.gcr.io/${PROJECT_ID}/${_PROJECT_NAME}:latest', '.']

- id: "Push Container Image to Google Container Registry"
  name: gcr.io/cloud-builders/docker
  args: ['push', 'eu.gcr.io/${PROJECT_ID}/${_PROJECT_NAME}:latest']

- id: "Deploy Container Image to Google Cloud Run"
  name: gcr.io/cloud-builders/gcloud
  args: ['run', 'deploy', '${_APP_NAME}',
         '--image', 'eu.gcr.io/${PROJECT_ID}/${_PROJECT_NAME}:latest',
         '--region', 'europe-west1',
         '--service-account', 'secret-manager-accesor@central-forge.iam.gserviceaccount.com',
         '--port', '8080',
         '--timeout', '1800',
         '--platform', 'managed',
         '--set-secrets', 'DEGIRO_USERNAME=DEGIRO_USERNAME:latest,DEGIRO_PASSWORD=DEGIRO_PASSWORD:latest,DEGIRO_TOTP_SECRET=DEGIRO_TOTP_SECRET:latest',
         '--allow-unauthenticated']

- id: "Delete old untagged container images"
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - '-c'
    - |
      for digest in $(gcloud container images list-tags eu.gcr.io/${PROJECT_ID}/${_PROJECT_NAME} --filter="NOT tags:latest" --format="get(digest)" 2>/dev/null); do
        gcloud container images delete "eu.gcr.io/${PROJECT_ID}/${_PROJECT_NAME}@$digest" --quiet --force-delete-tags 2>/dev/null || true
      done


timeout: 1200s
substitutions:
    _PROJECT_NAME: portfolio-tracker
    _APP_NAME: portfolio-tracker
